[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RedXAIEasyFunctions"
version = "1.0.1"


dynamic = [
    "description",       
    "readme",            
    "requires-python",    
    "authors",          
    "classifiers"        
]
